rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
gemfile:
  - Gemfile
  - Gemfile.edge
matrix:
  exclude:
    - gemfile: Gemfile
      rvm: jruby-head
    - gemfile: Gemfile
      rvm: jruby-19mode
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
